[package]
name = "chopper"
version = "0.7.1"
authors = ["wdecoster <decosterwouter@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bio = "1.3.1"
clap = { version = "4.2.1", features = ["derive"] }
rayon = "1.7.0"
approx = "0.5.1"
minimap2 = "0.1.17+minimap2.2.27"
flate2 = "1.0"
